# Import Statements

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso
from sklearn.linear_model import LassoCV
from sklearn.linear_model import Ridge
from sklearn.linear_model import RidgeCV
from sklearn.preprocessing import StandardScaler

# Creating Dataset

In [2]:
X1=np.random.randint(1,100,100)
X2=np.random.randint(1,100,100)
X3=np.random.randint(1,100,100)
X4=np.random.randint(1,100,100)
X5=np.random.randint(1,100,100)

In [3]:
X=np.column_stack((X1,X2,X3,X4,X5))

In [4]:
X

array([[87, 31, 51, 10, 35],
       [52, 55, 17, 67, 15],
       [76, 90, 20, 93, 17],
       [ 7, 72, 44, 35, 17],
       [86, 89, 64, 29, 87],
       [34, 68, 70, 30, 30],
       [66, 15, 78, 14, 78],
       [43, 86, 58, 56, 66],
       [81, 85,  6, 20, 71],
       [89, 32, 17, 38, 27],
       [14, 99, 37, 65, 10],
       [27, 99, 63, 55, 73],
       [14, 52, 13, 40, 28],
       [93, 45, 24, 87, 78],
       [70, 17, 78, 30, 99],
       [61, 94, 75,  9, 34],
       [66, 84, 62, 77, 44],
       [98, 87, 43, 13, 97],
       [82, 39, 50, 82, 12],
       [14, 35, 45,  6, 17],
       [23, 76, 72, 72, 26],
       [18, 30, 67, 54, 65],
       [31, 59, 62, 10, 20],
       [59, 93, 29, 63, 57],
       [67, 77, 57, 46, 80],
       [ 4, 46, 84, 22, 83],
       [39,  6, 27, 26, 32],
       [98, 64, 36, 26, 62],
       [40, 14, 73, 37,  3],
       [38, 53,  9, 78, 62],
       [35, 28, 29,  6, 99],
       [44, 52, 28, 51, 21],
       [86, 11, 73, 95, 11],
       [75, 29, 60, 78, 30],
       [12, 15

In [5]:
y=X1*3+X2*1+X3*0.6+X4*0+X5*0+np.random.rand(100)

In [6]:
y=y.reshape(-1,1)
y

array([[323.40442039],
       [221.73132366],
       [330.02806144],
       [119.51034866],
       [385.48979788],
       [212.74317821],
       [260.2562937 ],
       [250.70306369],
       [332.31078644],
       [309.58521336],
       [164.00709351],
       [218.59617923],
       [102.21592866],
       [339.03101642],
       [273.8746843 ],
       [322.05217327],
       [319.94237811],
       [407.58645702],
       [315.77077506],
       [104.58381486],
       [189.19698719],
       [124.27759454],
       [190.06931593],
       [287.83260497],
       [313.12942732],
       [108.95106547],
       [139.7443512 ],
       [379.78713193],
       [178.11093445],
       [172.99096882],
       [150.99380096],
       [201.48648725],
       [313.36399827],
       [290.52186626],
       [ 56.0097782 ],
       [286.69768752],
       [247.09474752],
       [304.0804591 ],
       [271.32857433],
       [127.38074101],
       [296.6246854 ],
       [241.19995798],
       [ 61.51298049],
       [ 64

# Splitting the Dataset

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.2)

# Declaring the parameters and hyperparameters

In [8]:
# theta=np.array([2,4,1,3,0])
# alpha=0.5
# lambda_=1

In [9]:
# for epoch in range(5000):
#     gradient=0
#     for i in range(80):
#         y_cap=np.dot(X_train[i],theta)
#         gradient+=(y_cap-y_train[i])*X_train[i]
#     gradient=(gradient)/80
#     theta = theta - alpha * (gradient + lambda_ * np.sign(theta))

# Scaling the data

In [10]:
sc=StandardScaler()

In [11]:
sc.fit(X_train)

StandardScaler()

In [12]:
X_train_scaled=sc.transform(X_train)

In [13]:
X_test_scaled=sc.transform(X_test)

In [14]:
X_train_scaled.min(),X_train_scaled.max()

(-1.6647532249772552, 1.8897288342676717)

# Lasso Regression

In [15]:
lasso=Lasso(alpha=1)

In [16]:
lasso.fit(X_train,y_train)

Lasso(alpha=1)

In [17]:
y_pred=lasso.predict(X_test)

In [18]:
lasso.score(X_test,y_test)

0.9999892955332067

In [19]:
from sklearn.metrics import r2_score

In [20]:
r2_score(y_test,y_pred)

0.9999892955332067

In [21]:
lasso.alpha

1

In [22]:
lasso.coef_

array([ 2.99842076,  1.00010306,  0.59943625,  0.        , -0.        ])

# LassoCV Regularization

In [23]:
lassocv=LassoCV()

In [24]:
lassocv.fit(X_train_scaled,y_train)

C:\Users\chaga\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:1623: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LassoCV()

In [25]:
y_pred=lassocv.predict(X_test_scaled)

In [26]:
lassocv.score(X_test_scaled,y_pred)

1.0

In [27]:
lassocv.alpha_

0.08425024358809144

In [28]:
lasso.coef_

array([ 2.99842076,  1.00010306,  0.59943625,  0.        , -0.        ])

# Observation
### The Lasso regression is able to find the unwanted features in the dataset

# Ridge Regression

In [29]:
ridge=Ridge(alpha=1)

In [30]:
ridge.fit(X_train_scaled,y_train)

Ridge(alpha=1)

In [31]:
y_pred=ridge.predict(X_test_scaled)

In [32]:
r2_score(y_pred,y_test)

0.9998117205693561

In [33]:
ridge.score(X_test_scaled,y_test)

0.9998161991725254

In [34]:
ridge.coef_

array([[83.0634462 , 30.66569137, 17.49813462,  0.10561709,  0.16234977]])